apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80         # This is the port exposed by the service
      targetPort: 5173  # This should match the containerPort from the deployment
  type: ClusterIP
