apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /authentication/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: authentication-service
                port:
                  number: 7000
          - path: /business-owner/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: business-owner-service
                port:
                  number: 7001
          - path: /payment/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: payment-service
                port:
                  number: 7005
          - path: /super-admin/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: super-admin-service
                port:
                  number: 7002
          - path: /employee/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: employee-service
                port:
                  number: 7004
          - path: /communication/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: communication-service
                port:
                  number: 7006
          - path: /manager/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: manager-service
                port:
                  number: 7003
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: manager-service
                port:
                  number: 7003
